# Generated by Django 2.0.5 on 2018-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_auto_20180514_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
