# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 17:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_pizzaorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.contrib.auth.models.AnonymousUser, to=settings.AUTH_USER_MODEL),
        ),
    ]
